---
- name: 'systemd | remove ntpd | ubuntu'
  include: ntpd-ubuntu-remove.yml

- name: 'systemd | remove ntpd | configuration'
  file:
    path: '/etc/ntp.conf'
    state: 'absent'
  become: yes

- name: 'systemd | configuration'
  template:
    src: 'timesyncd.j2'
    dest: '/etc/systemd/timesyncd.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  become: yes
  notify: 'reload systemd'

- name: 'systemd | service start'
  systemd:
    name: systemd-timesyncd.service
    enabled: yes
    state: started
  become: yes
