---
- name: 'restart ntp'
  become: yes
  service:
    name: 'ntp'
    state: 'restarted'

- name: 'reload systemd'
  systemd:
    name: systemd-timesyncd.service
    state: 'restarted'
    daemon_reload: yes
  become: yes
